defaults:
  - view_sampler: all

name: omniscene
roots: [datasets/omniscene]
make_baseline_1: false
augment: false

image_shape: [224, 400]
background_color: [0.0, 0.0, 0.0]
cameras_are_circular: false

baseline_epsilon: 1e-3
max_fov: 100.0

near: 0.5
far: 100.0
baseline_scale_bounds: false
shuffle_val: true
test_len: -1
train_times_per_scene: 1
skip_bad_shape: true
highres: false
